### ISSUE TITLE
Media condition gives errors

### ISSUE THREAD

**Issue by R4YM3** [rikschennink/conditioner-boilerplate-webpack#1]
I'm getting the message "Cannot find module '././monitors/media'" when using a media condition.

**Comment by rikschennink** [comment]
Hi! Just to let you know I received the issue, will look at it as soon as possible.

**Comment by rikschennink** [comment]
Very sorry for the delay. I've updated the example, had to make some small changes to the Conditioner library itself. The example now contains the media monitor and two different modules.

**Comment by rebelrebel82** [comment]
I just checked out your boilerplate example. It works with webpack version 1.13.3 but seems to fail with webpack 2.4.1. Could you please update the example so it works with the latest webpack release?
